package com.privacyguard.audit

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PolicyReportFormatter {

    fun generateComplaintBrief(audit: ComprehensiveAppAudit): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss z", Locale.US)
        val timestamp = dateFormat.format(Date())

        val sb = StringBuilder()
        sb.appendLine("====================================================")
        sb.appendLine("GOOGLE PLAY DEVELOPER POLICY VIOLATION REPORT")
        sb.appendLine("====================================================")
        sb.appendLine("Target App Name: ${audit.appName}")
        sb.appendLine("Target Package ID: ${audit.packageName}")
        sb.appendLine("Version: ${audit.versionName} (Build ${audit.versionCode})")
        sb.appendLine("Audit Timestamp: $timestamp")
        sb.appendLine("Target App Store: Google Play Store")
        sb.appendLine("Risk Assessment: ${audit.riskRating}")
        sb.appendLine()

        if (audit.policyViolations.isNotEmpty()) {
            sb.appendLine("FLAGGED POLICY BREACHES (${audit.policyViolations.size}):")
            sb.appendLine("----------------------------------------------------")
            audit.policyViolations.forEachIndexed { idx, violation ->
                sb.appendLine("[Violation ${idx + 1}] ${violation.title}")
                sb.appendLine("• Severity: ${violation.severity.label}")
                sb.appendLine("• Policy Section: ${violation.googlePlayPolicySection}")
                sb.appendLine("• Conflicting Permissions: ${violation.mismatchedPermissions.joinToString(", ")}")
                if (violation.offendingSdks.isNotEmpty()) {
                    sb.appendLine("• Offending SDKs: ${violation.offendingSdks.joinToString { "${it.name} (${it.signature})" }}")
                }
                sb.appendLine("• Observed Behavior: ${violation.observedBehavior}")
                sb.appendLine("• Policy Breach Clause: ${violation.policyBreachClause}")
                sb.appendLine("• Recommended Flag Category: ${violation.recommendedTakedownReason}")
                sb.appendLine()
            }
        }

        sb.appendLine("TECHNICAL MANIFEST & BINARY AUDIT:")
        sb.appendLine("----------------------------------------------------")
        sb.appendLine("• Declared Permissions (${audit.declaredPermissions.size}):")
        if (audit.declaredPermissions.isEmpty()) {
            sb.appendLine("  (None or restricted)")
        } else {
            audit.declaredPermissions.take(15).forEach { perm ->
                sb.appendLine("  - $perm")
            }
            if (audit.declaredPermissions.size > 15) {
                sb.appendLine("  - ... and ${audit.declaredPermissions.size - 15} additional permissions")
            }
        }
        sb.appendLine()

        sb.appendLine("• Embedded Commercial Telemetry / Ad Components (${audit.embeddedTrackers.size}):")
        if (audit.embeddedTrackers.isEmpty()) {
            sb.appendLine("  (No known commercial tracker SDKs identified)")
        } else {
            audit.embeddedTrackers.forEach { tracker ->
                sb.appendLine("  - ${tracker.name} [${tracker.category}] | Vendor: ${tracker.company} | Code Signature: ${tracker.signature}")
            }
        }
        sb.appendLine()

        sb.appendLine("RECOMMENDED GOOGLE PLAY TAKEDOWN REASON:")
        val topCategory = audit.policyViolations.firstOrNull()?.recommendedTakedownReason
            ?: "Data Safety & Privacy Violation / Unnecessary Sensitive Permissions"
        sb.appendLine(">> $topCategory")
        sb.appendLine()
        sb.appendLine("Automated Submission Action:")
        sb.appendLine("Submit via Google Play Store Listing -> 'Flag as inappropriate' or via:")
        sb.appendLine("https://support.google.com/googleplay/android-developer/contact/takedown")
        sb.appendLine()
        sb.appendLine("Generated by PrivacyGuard Open-Source Android Telemetry Monitor")
        sb.appendLine("====================================================")

        return sb.toString()
    }
}
